server:
port: 8086

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: bdjg1029@gmail.com
    password: ruowdltoxbmxxrlg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000 # 30* 60 = 30분
    default-encoding: UTF-8
# JWT 설정
jwt:
  issuer: yhyh
  header: Authorization
  secretKey: NiOeyFbN1Gqo10bPgUyTFsRMkJpGLXSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI
  access-token-validity-in-seconds: 360000

# API 설정
app:
  email-verification:
    code-expiration-minutes:5
  api:
    url: http://localhost:8080
    # production-url: http://j11a604.p.ssafy.io:8081/

# 외부 API 키 설정
API_KEY: ${API_KEY}

# Eureka 설정
eureka:
  client:
    register-with-eureka: true  # Eureka에 서비스 등록 여부
    fetch-registry: true  # Eureka 레지스트리 정보를 클라이언트가 가져오는지 여부
    service-url:
      defaultZone: http://j11a604.p.ssafy.io:8761/eureka # Eureka 서버 URL (여기에 맞게 변경하세요)

# 관리 엔드포인트 설정
management:
  endpoint:
    web:
      exposure:
        include: "*"  # 모든 엔드포인트를 노출시킴

# 로깅 설정
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.hibernate: DEBUG
    org.springframework: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.security: DEBUG
