spring:
  datasource:
    url: jdbc:mysql://j11a604.p.ssafy.io:3306/trabean?useSSL=false&serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: notification
server:
  port: 8083