spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: NOTIFICATION
  profiles:
    active: local

server:
  port: 8083

# Eureka ??
eureka:
  #  instance:
  #    prefer-ip-address: true  # ???? ?? ? IP ??? ??
  # 위 설정을 사용하면 해당 서버를 ip로 찾아야하기 때문에 서버 이름으로 올바른 서버를 찾지 못한다.
  client:
    register-with-eureka: true  # Eureka ??? ?? ??
    fetch-registry: true  # Eureka ???? ??? ??? ??? ???? ??
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka ??? ?? URL (??? ?? URL? ???? ?)

# ?? ????? ??
management:
  endpoint:
    web:
      exposure:
        include: "*"  # ?? ?? ????? ??


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    root: INFO
