# ?? ??
server:
  port: 80  # ??????? ??? ?? ??

# Eureka ??
eureka:
  client:
    register-with-eureka: true  # Eureka ??? ?? ??
    fetch-registry: true  # Eureka ???? ??? ??? ??? ???? ??
    service-url:
      defaultZone: http://j11a604.p.ssafy.io:8761/eureka # Eureka ??? ?? URL (??? ?? URL? ???? ?)

# Spring ?????? ??
spring:
  application:
    name: gateway  # ??????? ?? ??

  # Spring Cloud Gateway ??
  cloud:
    gateway:
      routes: # ??? ?? ??아
        - id: accountRoute  # ??? ID
          uri: lb://ACCOUNT # ??? ??? URI (??? ?? URI? ???? ?)
          filters:
            - name: GatewayLoggingFilter  # 로깅 필터 추가
          predicates: # ??? ????? ??
            - Path=/api/accounts/**  # /account/** ??? ?? ??? ??

        - id: chatbotRoute
          uri: lb://CHATBOT
          filters:
            - name: GatewayLoggingFilter  # 로깅 필터 추가
          predicates:
            - Path=/api/chatbot/**

        - id: notificationRoute
          #          uri: http://j11a604.p.ssafy.io:8083

          uri: lb://NOTIFICATION
          filters:
            - name: GatewayLoggingFilter  # 로깅 필터 추가
          predicates:
            - Path=/api/notification/**

        - id: paymentRoute
          uri: lb://PAYMENT
          filters:
            - name: GatewayLoggingFilter  # 로깅 필터 추가
          predicates:
            - Path=/api/payments/**

        - id: travelRoute
          uri: lb://TRAVEL
          filters:
            - name: GatewayLoggingFilter  # 로깅 필터 추가
          predicates:
            - Path=/api/travel/**

        - id: userRoute
          uri: lb://USER
          filters:
            - name: GatewayLoggingFilter  # 로깅 필터 추가
          predicates:
            - Path=/api/user/**



logging:
  level:
    root: INFO
    com.trabean.gateway.filter.GatewayLoggingFilter: DEBUG  # 필터가 있는 패키지 경로로 변경
