# ?? ??
server:
  port: 80  # ??????? ??? ?? ??

# Spring ?????? ??
spring:
  application:
    name: gateway  # ??????? ?? ??

  # Spring Cloud Gateway ??
  cloud:
    gateway:
      mvc:
        routes: # ??? ?? ??아
          - id: accountRoute  # ??? ID
            uri: http://j11a604.p.ssafy.io:8081 # ??? ??? URI (??? ?? URI? ???? ?)
            predicates: # ??? ????? ??
              - Path=/account/**  # /account/** ??? ?? ??? ??

          - id: chatbotRoute
            uri: http://j11a604.p.ssafy.io:8082
            predicates:
              - Path=/chatbot/**

          - id: notificationRoute
            uri: http://j11a604.p.ssafy.io:8083
            predicates:
              - Path=/notification/**

          - id: paymentRoute
            uri: http://j11a604.p.ssafy.io:8084
            predicates:
              - Path=/payment/**

          - id: travelRoute
            uri: http://j11a604.p.ssafy.io:8085
            predicates:
              - Path=/travel/**

          - id: userRoute
            uri: http://j11a604.p.ssafy.io:8086
            predicates:
              - Path=/user/**
# Eureka ??
eureka:
  instance:
    prefer-ip-address: true  # ???? ?? ? IP ??? ??
  client:
    register-with-eureka: true  # Eureka ??? ?? ??
    fetch-registry: true  # Eureka ???? ??? ??? ??? ???? ??
    service-url:
      defaultZone: http://j11a604.p.ssafy.io:8761/eureka # Eureka ??? ?? URL (??? ?? URL? ???? ?)

# ?? ????? ??
management:
  endpoint:
    web:
      exposure:
        include: "*"  # ?? ?? ????? ??
