# ?? ??
server:
  port: 80  # ??????? ??? ?? ??

# Eureka ??
eureka:
  instance:
    hostname: j11a604.p.ssafy.io
  client:
    register-with-eureka: true  # Eureka ??? ?? ??
    fetch-registry: true  # Eureka ???? ??? ??? ??? ???? ??
    service-url:
      defaultZone: http://j11a604.p.ssafy.io:8761/eureka # Eureka ??? ?? URL (??? ?? URL? ???? ?)

# Spring ?????? ??
spring:
  application:
    name: gateway  # 애플리케이션 이름 설정

  # Spring Cloud Gateway 설정
  cloud:
    gateway:
      # 기본 필터 설정 (필요에 따라 주석 해제)
      default-filters:
        #        - name: JwtFilter
        #          args:
        #            baseMessage: Spring Cloud Gateway Global Filter
        #            preLogger: true
        #            postLogger: true
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        cors-configurations:
          '[/**]': # 모든 경로에 대한 CORS 설정
            allowedOrigins:
              - "http://localhost:3000"
              - "https://j11a604.p.ssafy.io"  # 허용하는 출처
            allow-credentials: true  # 인증 정보 허용
            allowedHeaders: '*'  # 허용하는 헤더
            allowedMethods: # 허용하는 HTTP 메서드
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
              - PATCH

      routes: # ??? ?? ??아
        - id: accountRoute
          uri: lb://ACCOUNT
          predicates:
            - Path=/api/accounts/**
          filters:
            - name: JwtFilter  # JwtFilter를 이 라우트에 적용

        - id: chatbotRoute
          uri: lb://CHATBOT
          predicates:
            - Path=/api/chatbot/**
          filters:
            - name: JwtFilter  # JwtFilter를 이 라우트에 적용

        - id: notificationRoute
          #          uri: http://j11a604.p.ssafy.io:8083
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: JwtFilter  # JwtFilter를 이 라우트에 적용

        - id: paymentRoute
          uri: lb://PAYMENT
          predicates:
            - Path=/api/payments/**
          filters:
            - name: JwtFilter  # JwtFilter를 이 라우트에 적용

        - id: travelRoute
          uri: lb://TRAVEL
          predicates:
            - Path=/api/travel/**
          filters:
            - name: JwtFilter  # JwtFilter를 이 라우트에 적용

        - id: userRoute
          uri: lb://USER
          predicates:
            - Path=/api/user/**


logging:
  level:
    root: info # 전체 로그 레벨을 info 설정


