
server:
  port: 8761  # ??? ??? ?? ??? 8761? ?????.

spring:
  application:
    name: eureka  # ??????? ??? 'eureka'? ?????.


eureka:
  client:
    register-with-eureka: false  # ? ??? Eureka ???? ????? ?? Eureka ??? ???? ??? ?????.
    fetch-registry: false  # ?? Eureka ????? ??? ?? ??? ???? ??? ?????.

