spring:
  application:
    name: eureka  # ??????? ??? 'eureka'? ?????.

server:
  port: 8761  # ??? ??? ?? ??? 8761? ?????.

eureka:
  client:
    register-with-eureka: false  # ? ??? Eureka ???? ????? ?? Eureka ??? ???? ??? ?????.
    fetch-registry: false  # ?? Eureka ????? ??? ?? ??? ???? ??? ?????.
    # false? ???? ??? ? ???? ??? ??? ???? ??? ?? ??? ????? ??? ????? ??? ??? ??

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ?? ?? ?????? ??? ????? ?????.
